global:
  scrape_interval: 1s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: vault
    static_configs:
      - targets: ["vault:8202"]
    metrics_path: /v1/sys/metrics
    params:
      format: ["prometheus"]
    bearer_token_file: /etc/prometheus/vault-scrape-token

  - job_name: badapp
    static_configs:
      - targets: ["badapp:8080"]
